FROM alpine:3.21

RUN apk add python3 py3-pip make nodejs npm
RUN rm -rf /var/cache/apk/*

RUN adduser -D ytod
RUN mkdir /ytod
WORKDIR /ytod

RUN mkdir -p workdir
COPY requirements.txt requirements.txt
COPY Makefile Makefile
COPY wwwsrc wwwsrc

RUN chown -R ytod:ytod /ytod

RUN python -m venv venv
RUN ./venv/bin/pip install -r requirements.txt

COPY ytod ytod

# Tests to run:
RUN (cd wwwsrc; make)
RUN make test

ENTRYPOINT [ "sleep", "infinity" ]
# ENTRYPOINT [ "/bin/sh" ]

