FROM alpine:3.21

RUN apk add python3 py3-pip make

RUN adduser -D ytod
RUN mkdir /ytod
WORKDIR /ytod

RUN mkdir -p workdir
COPY requirements.txt requirements.txt
COPY Makefile Makefile

RUN chown -R ytod:ytod /ytod

RUN python -m venv venv
RUN ./venv/bin/pip install -r requirements.txt

COPY ytod ytod

ENTRYPOINT [ "make", "test" ]
# ENTRYPOINT [ "/bin/sh" ]

